### ISSUE TITLE
增加广告拦截功能插件

### ISSUE THREAD

**Issue by luis5540** [wukongdaily/gl-inet-onescript#1]
希望可以在懒人包中 添加广告拦截功能adguard home ，等等功能

**Comment by wukongdaily** [comment]
adguardhome 是mt3000和mt2500A 系统自带软件，你可以在 http://192.168.8.1/#/plugins ，软件包的搜索栏自行搜索 关键字，比如 : adg ,就可以找到一个大概10MB左右的安装包，点击安装即可。
安装成功后访问特定的端口3000 也就是访问
http://192.168.8.1:3000/ 
进行配置等

**Comment by wukongdaily** [comment]
![45646](https://github.com/wukongdaily/gl-inet-onescript/assets/143675923/18549465-5621-4199-aa93-7a94ededdcdb)
