### ISSUE TITLE
mt6000 能出一个脚本吗？

### ISSUE THREAD

**Issue by sauween** [wukongdaily/gl-inet-onescript#10]
MT3000 在线脚本安装成功
但是MT6000 找了很多方案 clash都安装不成功

**Comment by wukongdaily** [comment]
目前U盘版已经包括了mt6000. 不过ssrp和passwall 暂时在mt6000上没法用，但是openclash 可以。建议去油管看看那个视频。
https://github.com/wukongdaily/gl-inet-onescript/releases/tag/20231116
