### ISSUE TITLE
SSH登录后看不到U盘的挂载点

### ISSUE THREAD

**Issue by dead-lee** [wukongdaily/gl-inet-onescript#11]
我可以在管理前台看到插上的U盘，但是SSH登录后，输入df，看不到U盘的挂载点。
我用的是google网盘上最新的image刷的U盘。
![192 168 8 1#nasview](https://github.com/wukongdaily/gl-inet-onescript/assets/458074/db658467-853c-48c0-af6c-6db29d87a65d)
![IMG_8ADF0C8EE02E-1](https://github.com/wukongdaily/gl-inet-onescript/assets/458074/b363d5fa-13c3-45ee-9c53-bf6994776f2e)

**Comment by wukongdaily** [comment]
一般重启就能看到了。再不行就换个u盘试试。
