### ISSUE TITLE
mt6000版本v4.5.8_0402bate安装主题失败

### ISSUE THREAD

**Issue by youtuxp** [wukongdaily/gl-inet-onescript#15]
如图,是第2条备用命令不行：wget -O gl-inet.sh https://mirror.ghproxy.com/https://raw.githubusercontent.com/wukongdaily/gl-inet-onescript/master/gl-inet.sh?$(date +%s) && chmod +x gl-inet.sh && ./gl-inet.sh
 换第一条就成功了。

![Uploading iShot_2024-04-05_00.28.39.png…]()

**Comment by wukongdaily** [comment]
图片挂了。看不到了。

**Comment by youtuxp** [comment]
> 图片挂了。看不到了。
不知道怎么回事，图片上传不了。看记录吧。
`Updated List of available packages in /var/opkg-lists/istore_compat
Downloading https://fw.gl-inet. cn/ releases/mt 798x/kmod-4.5.7/aarch64_cortex-a53/ mediate
k/mt7986/Packages.gz
Updated List of available packages in /var/opkg-lists/glinet_core
DownLoading https://fw.gl-inet. cn/ releases/mt 798x/packages-4.5/aarch64_cortex-a53/gline
t/Packages.gz
Updated List of available packages in /var/ opkg-lists/glinet_gli_pub
Downloading https:// fw.gl-inet.cn/ releases/ mt798x/packages-4,5/aarch64_cortex-a53/packa
ges/Packages.gZ
Updated list of available packages in /var /opkg-lists/glinet_gli_packages
Updating database.
Database update completed.
Package Luci-lib-ipkg (git-18.318.71164-4bbe325) installed in root is up to date.
Updating database.
Database update completed.
Downloading "https://raw. githubusercontent. com/wukongdaily/gl- inet-onescript/ master/the
me/luci-theme-argon-master_2.2.9.4_all.ipk"
Connecting to :::443
Connection error: Invalid SSL certificate
Downloading "https://raw.githubusercontent.com/wukongdaily/gl- inet -onescript/ master/ the
me/luci-app-argon-config_0.9_all.ipk'
Connecting to:::443
Connection error: Invalid SSL certificate
DownLoading "https:// raw.githubusercontent.com/wukongdaily/gl-inet-onescript/ master/the
me/luci-i18n-argon- config-zh-cn.ipk'
Connecting to:::443
Connection error: Invalid SSL certificate
Collected errors:
* wfopen:Luci-theme-argon.ipk： No such file or directory.
* pkg_init_from file: Failed to extract control file from Luci- theme-argon.ipk.
argon主题 安装失败！建议再执行一次！再给我一个机会！事不过三！
按 Enter 键继续..`

**Comment by wukongdaily** [comment]
说白了 就是github文件 在大陆访问不了的事情。加了代理，用下面的命令吧。
```bash
wget -O gl-inet.sh https://mirror.ghproxy.com/https://raw.githubusercontent.com/wukongdaily/gl-inet-onescript/master/gl-inet.sh && chmod +x gl-inet.sh 
sh gl-inet.sh use_proxy
```
