### ISSUE TITLE
mt6000 安装docker失败，usb硬盘未识别

### ISSUE THREAD

**Issue by xqdd** [wukongdaily/gl-inet-onescript#16]
![image](https://github.com/wukongdaily/gl-inet-onescript/assets/20871761/fb53b216-900e-41cd-aace-1ca1f6eeabce)

![image](https://github.com/wukongdaily/gl-inet-onescript/assets/20871761/41fb2c25-a769-40ca-ae47-eb1cc76a532b)

**Comment by wukongdaily** [comment]
提醒：你的硬盘里是有数据的，这个操作会格式化硬盘的。所以首先把你的数据先做好备份。
然后你可以先用电脑把它从新格式化一次。然后在用我的工具。
