### ISSUE TITLE
mirror.ghproxy.com好像也被墙了

### ISSUE THREAD

**Issue by dead-lee** [wukongdaily/gl-inet-onescript#17]
无法下载了，能把扩容这个事情，也做成u盘版本吗。
我现在是：
1. 升级路由器。
2. 用U盘版本脚本搞定科学上网。但是现在u盘版本执行出错：
请选择一个选项: 1
do_istore method==================>
curl: (6) Could not resolve host: istore.linkease.com
zcat: short read

3. 在用能科学上网后的版本去搞扩容。。卡在第二步也走不下去了。

相当折腾。

Downloading 'https://mirror.ghproxy.com/https://raw.githubusercontent.com/wukongdaily/gl-inet-onescript/master/mt-3000/mt3000.sh'
Failed to send request: Operation not permitted
sh: can't open 'mt3000.sh': No such file or directory

**Comment by dead-lee** [comment]
现在gfw太严，我在想，u盘版应该保证全程离线安装，保证能科学上网先，再去用在线的一键更新。

**Comment by dead-lee** [comment]
为啥直接关了呢，是有解决方案了吗？

**Comment by wukongdaily** [comment]
嗯～有方案啦。目前是采用自建仓库的方式。没墙啦～
https://cafe.cpolar.cn/wkdaily/gl-inet-onescript
