### ISSUE TITLE
passwall呢

### ISSUE THREAD

**Issue by sauween** [wukongdaily/gl-inet-onescript#19]
之前我记得有 一键passwall 现在 没了吗

**Comment by wukongdaily** [comment]
因为这些插件不断更新，有些新版反而不能兼容，毕竟是硬路由。所以建议自行在istore商店手动安装。

**Comment by sauween** [comment]
有道理，但是 我就是这么懒啊

**Comment by ccwforever** [comment]
大佬，想问一下先一键istore脚本，然后本地安装passwall，为什么不管怎么操作都显示tcp未运行呀，那几个报缺少的软件包安装了也没用
