### ISSUE TITLE
MT6000使用4.6.4-op24版本安装，安装时报错

### ISSUE THREAD

**Issue by jelipo** [wukongdaily/gl-inet-onescript#27]
OP是24版本，安装时会报错，但是最后可以安装成功，一些组件安装时会报错

固件链接： [https://dl.gl-inet.com/router/mt6000/](https://dl.gl-inet.com/router/mt6000/)

![image](https://github.com/user-attachments/assets/1e8c1488-130b-444b-b983-7e266b7746f7)

**Comment by wukongdaily** [comment]
我的脚本只适用于官方原版satble固件。
