### ISSUE TITLE
ssl

### ISSUE THREAD

**Issue by Jehuge** [wukongdaily/gl-inet-onescript#28]
SSL routines:ssl3_get_record:wrong version number
zcat: short read

**Comment by wukongdaily** [comment]
OK 看到了。别着急 过几天它就自动变好啦。因为最近istore的软件中心坏了，我脚本也调用了它们的软件源，所以卡在这里。等过几天小宝修复了。我这边也就自动恢复了。详细的原因看这个视频：https://www.bilibili.com/video/BV1QgmtYdENo

**Comment by wukongdaily** [comment]
https://github.com/wukongdaily/gl-inet-onescript/commit/9b1836b2490f7ee827100061bf8cdbb4114d56eb
已修复，请重新之行即可
