### ISSUE TITLE
安装的时候出错

### ISSUE THREAD

**Issue by znmax** [wukongdaily/gl-inet-onescript#3]
Connecting to :::443
Connection error: Invalid SSL certificate
不知道什么原因。时区已经设置成shanghai了

**Comment by wukongdaily** [comment]
> 国内访问失败，原先的国内反代被关了，我看git记录原先是使用ghproxy反代了，现在反代取消了，就算ghproxy被墙还有gh-proxy可以用啊为什么直接取消反代，这就是暂时不让国内机器直接使用，为什么？作者害怕用的人太多出事？

ghproxy.com目前不挂梯访问不到。可能是被墙了吧。其他代理我没尝试过，目前没找到什么好而稳定的，毕竟这些代理也是用爱发电（表示尊重）。可能持久不了。如果三天两头的换，也不是个事。所以先去掉了。建议使用u盘安装iStore，参考readme。剩下的 手动安装一下就好。
