### ISSUE TITLE
运行 drive-gl-inet.sh 提示line 8: syntax error: unexpected newline

### ISSUE THREAD

**Issue by haha110110** [wukongdaily/gl-inet-onescript#4]
mt-3000 v.4.4.6版本
drive-gl-inet.sh下载到路由器 /tmp下，chomd +x  这个文件。然后运行提示：
8: syntax error: unexpected newline

**Comment by wukongdaily** [comment]
`sh  /tmp/drive-gl-inet.sh`
你是上述方法执行的吗。实在不行你就先安装应用商店吧。采用u盘+ssh方式安装：https://telegra.ph/install-istore-for-mt3000-11-03

**Comment by haha110110** [comment]
离线的不行，不过我给路由器也连上国际互联网后直接执行命令后是可以运行的。
