### ISSUE TITLE
按H键后 无法换回就菜单

### ISSUE THREAD

**Issue by ramboaccp** [wukongdaily/gl-inet-onescript#5]
按H键后 无法换回就菜单  
反馈内容如下：

<img width="876" alt="1699836792918" src="https://github.com/wukongdaily/gl-inet-onescript/assets/100740907/fb34dc84-19df-487e-b0a6-1a9ff7ba1602">

**Comment by wukongdaily** [comment]
OK,我一会修改bug。这边给你先提供一个临时的办法。先执行如下代码之后，再从新执行脚本即可。

`opkg update`
`opkg install bash`

**Comment by wukongdaily** [comment]
https://github.com/wukongdaily/gl-inet-onescript/commit/b4856da740690b5e4894ac23ee0d2d7ee7f2e337
已解决
