### ISSUE TITLE
如果登录路由器，是以内部域名形式登录的，那么3大科学上网插件的抬头菜单项是英文的

### ISSUE THREAD

**Issue by phunics** [wukongdaily/gl-inet-onescript#6]
**如果登录路由器，是以IP地址登录的，那么3大科学上网插件的抬头菜单项是中文的，但如果是以内部域名形式登录的，则菜单项就变成了英文的**
![image](https://github.com/wukongdaily/gl-inet-onescript/assets/128953061/e0c92761-f302-4de4-b358-2effc38c4048)
![image](https://github.com/wukongdaily/gl-inet-onescript/assets/128953061/3f084397-c8d8-4af9-bf16-333e0461e3dd)

**【如何设置内部域名】**

![image](https://github.com/wukongdaily/gl-inet-onescript/assets/128953061/6ac83d5b-24a1-4a9b-bd3d-05776303be31)

**Comment by wukongdaily** [comment]
当抬头出现英文的时候，建议在页面 强制刷新。如果是 Chrome浏览器，按住 ⇧ Shift 键并按 R 键。

**Comment by phunics** [comment]
感谢指导，我的是Edge浏览器，按住CTRL+F5可以解决，谢谢
