### ISSUE TITLE
在使用脚本安装ADGUARD后的提示优化

### ISSUE THREAD

**Issue by zhangsubo** [wukongdaily/gl-inet-onescript#7]
在使用脚本完成 ADGUARD 后，会提示前往 https://192.168.8.1:3000 进行设置，建议网址可以根据路由器实际的本地网址进行展示，比如我已经调整成了 192.168.1.1 但是还是会提示前往 192.168.8.1。

**Comment by wukongdaily** [comment]
感谢您的反馈，已解决：https://github.com/wukongdaily/gl-inet-onescript/commit/1f7832005ae6916a41689723def44c2ea29bc45b
